# Form implementation generated from reading ui file '.\browser.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 364)
        Form.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        Form.setWindowTitle("")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.browserLayout = QtWidgets.QVBoxLayout()
        self.browserLayout.setObjectName("browserLayout")
        self.searchFrame = QtWidgets.QFrame(parent=Form)
        self.searchFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.searchFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.searchFrame.setObjectName("searchFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.searchFrame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.searchBar = QtWidgets.QLineEdit(parent=self.searchFrame)
        self.searchBar.setObjectName("searchBar")
        self.horizontalLayout_2.addWidget(self.searchBar)
        self.searchButton = QtWidgets.QPushButton(parent=self.searchFrame)
        self.searchButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.searchButton.setObjectName("searchButton")
        self.horizontalLayout_2.addWidget(self.searchButton)
        self.filterButton = QtWidgets.QPushButton(parent=self.searchFrame)
        self.filterButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.filterButton.setObjectName("filterButton")
        self.horizontalLayout_2.addWidget(self.filterButton)
        self.browserLayout.addWidget(self.searchFrame)
        self.mangasFrame = QtWidgets.QFrame(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mangasFrame.sizePolicy().hasHeightForWidth())
        self.mangasFrame.setSizePolicy(sizePolicy)
        self.mangasFrame.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.mangasFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.mangasFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.mangasFrame.setObjectName("mangasFrame")
        self.mangasLayout = QtWidgets.QVBoxLayout(self.mangasFrame)
        self.mangasLayout.setObjectName("mangasLayout")
        self.browserLayout.addWidget(self.mangasFrame)
        self.horizontalLayout.addLayout(self.browserLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.searchButton.setText(_translate("Form", "Поиск"))
        self.filterButton.setText(_translate("Form", "Фильтры"))
