# Form implementation generated from reading ui file '.\manga_preview_widget.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_manga_widget(object):
    def setupUi(self, manga_widget):
        manga_widget.setObjectName("manga_widget")
        manga_widget.resize(240, 340)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(manga_widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.manga_frame = QtWidgets.QFrame(parent=manga_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manga_frame.sizePolicy().hasHeightForWidth())
        self.manga_frame.setSizePolicy(sizePolicy)
        self.manga_frame.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.manga_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.manga_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.manga_frame.setObjectName("manga_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.manga_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.image = QtWidgets.QLabel(parent=self.manga_frame)
        self.image.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.image.setObjectName("image")
        self.verticalLayout.addWidget(self.image)
        spacerItem = QtWidgets.QSpacerItem(20, 273, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.name = QtWidgets.QLabel(parent=self.manga_frame)
        self.name.setObjectName("name")
        self.verticalLayout.addWidget(self.name)
        self.verticalLayout_2.addWidget(self.manga_frame)

        self.retranslateUi(manga_widget)
        QtCore.QMetaObject.connectSlotsByName(manga_widget)

    def retranslateUi(self, manga_widget):
        _translate = QtCore.QCoreApplication.translate
        manga_widget.setWindowTitle(_translate("manga_widget", "Form"))
        self.image.setText(_translate("manga_widget", "Image"))
        self.name.setText(_translate("manga_widget", "Name"))
